public with sharing class tmdbSearchMovieResult {
    @AuraEnabled
    public Boolean adult;
    @AuraEnabled
    public String backdrop_path;
    @AuraEnabled
    public List<Integer> genre_ids;
    @AuraEnabled
    public Integer id;
    @AuraEnabled
    public String original_language;
    @AuraEnabled
    public String original_title;
    @AuraEnabled
    public String overview;
    @AuraEnabled
    public Decimal popularity;
    @AuraEnabled
    public String poster_path;
    @AuraEnabled
    public String release_date;
    @AuraEnabled
    public String title;
    @AuraEnabled
    public Boolean video;
    @AuraEnabled
    public Decimal vote_average;
    @AuraEnabled
    public Integer vote_count;
}
